a=str(input("primul cuvant "))
b=str(input("al doilea cuvant "))
c=str(input("al treilea cuvant "))
d=str(input("al patrulea cuvant "))
print(a)
print(b)
print(c)
print(d)
print(a+" "+b+" "+c+" "+d+".")